#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <climits>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
using namespace std;template<typename T>class cppp_smart_pointer{struct Block{size_t refcount=1;T data;template<typename...Args>explicit Block(Args&&...args):data(std::forward<Args>(args)...){}};Block*block=nullptr;void addref(){if(block)++block->refcount;}void delref(){if(block&&--block->refcount==0)delete block;}public:cppp_smart_pointer()=default;cppp_smart_pointer(nullptr_t){}cppp_smart_pointer(const cppp_smart_pointer&other):block(other.block){addref();}cppp_smart_pointer(cppp_smart_pointer&&other)noexcept:block(other.block){other.block=nullptr;}~cppp_smart_pointer(){delref();}cppp_smart_pointer&operator=(const cppp_smart_pointer&other){if(this!=&other){Block*replacement=other.block;if(replacement)++replacement->refcount;delref();block=replacement;}return*this;}cppp_smart_pointer&operator=(cppp_smart_pointer&&other)noexcept{if(this!=&other){Block*replacement=other.block;other.block=nullptr;delref();block=replacement;}return*this;}cppp_smart_pointer&operator=(nullptr_t){delref();block=nullptr;return*this;}template<typename...Args>static cppp_smart_pointer make(Args&&...args){cppp_smart_pointer result;result.block=new Block(std::forward<Args>(args)...);return result;}T*operator->(){return&block->data;}const T*operator->()const{return&block->data;}T&operator*(){return block->data;}const T&operator*()const{return block->data;}explicit operator bool()const{return block!=nullptr;}bool operator==(nullptr_t)const{return block==nullptr;}bool operator!=(nullptr_t)const{return block!=nullptr;}friend bool operator==(nullptr_t,const cppp_smart_pointer&value){return value==nullptr;}friend bool operator!=(nullptr_t,const cppp_smart_pointer&value){return value!=nullptr;}};long long CPPPInputInt(){long long value;if(!(cin>>value))throw runtime_error("invalid input: expected int");return value;}template<typename A,typename B>class CPPPPair;template<typename T>class CPPPList;template<typename T>class CPPPHeap;template<typename T>class CPPPSet;template<typename K,typename V>class CPPPMap;struct CPPPRange;template<typename T>void CPPPPrintValue(ostream&output,const T&value);template<typename A,typename B>void CPPPPrintValue(ostream&output,const CPPPPair<A,B>&value);template<typename T>void CPPPPrintValue(ostream&output,const CPPPList<T>&values);template<typename T>void CPPPPrintValue(ostream&output,const CPPPHeap<T>&values);template<typename T>void CPPPPrintValue(ostream&output,const CPPPSet<T>&values);template<typename K,typename V>void CPPPPrintValue(ostream&output,const CPPPMap<K,V>&values);void CPPPPrintValue(ostream&output,const CPPPRange&values);template<typename T>void CPPPPrintValue(ostream&output,const cppp_smart_pointer<T>&value){if(!value){output<<"NULL";return;}CPPPPrintValue(output,*value);}template<typename T>void CPPPPrintValue(ostream&output,const T&value){output<<value;}int main(){ios::sync_with_stdio(false);cin.tie(nullptr);long long x=CPPPInputInt(),p1_off=CPPPInputInt(),p2_off=CPPPInputInt(),p3_off=CPPPInputInt();long long p0=((((x+p1_off)+p2_off)+p3_off)/4);{auto __cppp_describe_value_0=p0;cout<<"p0: ";CPPPPrintValue(cout,__cppp_describe_value_0);cout<<", ";auto __cppp_describe_value_1=(p0-p1_off);cout<<"p0 - p1_off: ";CPPPPrintValue(cout,__cppp_describe_value_1);cout<<", ";auto __cppp_describe_value_2=(p0-p2_off);cout<<"p0 - p2_off: ";CPPPPrintValue(cout,__cppp_describe_value_2);cout<<", ";auto __cppp_describe_value_3=(p0-p3_off);cout<<"p0 - p3_off: ";CPPPPrintValue(cout,__cppp_describe_value_3);cout<<'\n';}return 0;}
